# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.0.1
          - eslint-config-prettier@9.1.0
          - eslint-plugin-import@2.25.2
          - eslint-plugin-n@15.0.0
          - eslint-plugin-promise@6.0.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-black
        language_version: python3.10
      - id: nbqa-check-ast
        language_version: python3.10
      - id: nbqa-flake8
        language_version: python3.10
      - id: nbqa-isort
        language_version: python3.10
      - id: nbqa-mypy
        language_version: python3.10
        args:
          - --ignore-missing-imports
      - id: nbqa-pylint
        language_version: python3.10
        args:
          - --disable=C0114
          - --ignored-modules=numpy,pandas,scipy.stats,seaborn
